### ISSUE TITLE
Sprockets fails to compile colorpicker.less even though it is not required

### ISSUE THREAD

**Issue by j0ni** [kristianmandrup/bootstrap-addons-rails#8]
When precompiling assets, I see the following:

```
.border-radius is undefined
  (in /Users/joni/Valassis/Code/github/deployment/myapp/vendor/ruby/1.9.1/gems/bootstrap-addons-rails-0.1.2/vendor/assets/colorpicker/less/colorpicker.less)
at /Users/joni/Valassis/Code/github/deployment/myapp/vendor/ruby/1.9.1/gems/less-2.2.1/lib/less/js/lib/less/parser.js:385:31
```

despite not having included any require statements or @imports for colorpicker. In fact, all I do is //= require image-gallery and its dependency in the javascripts manifest, and only @import "bootstrap/image-gallery.css"; in my _bootstrap_and_overrides.scss file.

Any ideas? Also let me know if there is more info I can provide.

**Comment by kristianmandrup** [comment]
See the new "gotchas" section in the README. Hope that helps ;)

**Comment by j0ni** [comment]
Thank you.
