### ISSUE TITLE
Current version of image gallery is incompatible with Bootstrap 3

### ISSUE THREAD

**Issue by eric-smartlove** [kristianmandrup/bootstrap-addons-rails#9]
Current version of image gallery is 2.10, but we need image gallery 3.0.0+ if we want to use it with Bootstrap 3.

I would prefer to make a pull request instead of opening this issue but my knowledge of asset pipeline and javascript components is too limited.

**Comment by kristianmandrup** [comment]
Please fork this project and create your own gem, fx _bootstrap3-addons-rails_. The asset pipeline is very simple. You simply put your assets in vendor/assets folder in preordained folders such as stylesheets/ and javascripts/ etc. like done here. I'm not using Rails anymore, switched to Node.js instead ;)
